/*
Inserts the speakers from 2012
*/
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (0, "Ian", "Ratner", 8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (1, "Ram", "Karra", 8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (2,"Deborah","Cliburn",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (3,"Prashanth","Chakrapani",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (4,"Scott","Cruze",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (5,"Mark","Kelly",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (6,"Jim","Senter",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (7,"Phil","Spann",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (8,"Jeffrey","Allen",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (9,"Bhaumik","Shah",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (10,"Panagiotis","Tzerefos",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (11,"Ben","Pack",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (12,"David","Tucker",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (13,"Matt","Peter",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (14,"Pedro","Lopez",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (15,"John","Hills",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (16,"Bryan","Fails",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (17,"Glen","Wright",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (18,"Kevin","Barry",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (19,"Jeffery","Kissinger",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (20,"Beth","Jackson",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (21,"Brian","Hinsley",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (22,"Drew","Fredrick",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (23,"Glen","Ireland",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (24,"Robert","Clarence",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (25,"Sarah","Cottay",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (26,"Channing","Dawson",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (27,"Mike","Campbell",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (28,"Joshua","Eldridge",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (29,"Bruce","Parker",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (30,"Robin","Wilde",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (31,"Lydia","Cordell",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (32,"Team","Nirvana",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (33,"Amy","Thomason",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (34,"Charles","Lewis",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (35,"Jonathan","Williams",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (36,"Scott","Gentry",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (37,"Jason","Norton",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (38,"Michael","Wehrle",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (39,"Shane","Closser",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (40,"Selene","Tolbert",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (41,"Michael","Berger",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (42,"Kamlesh","Sharma",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (43,"Kabita","Nayak",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (44,"Herb","Himes",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (45,"Stefanie","Edinger",8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (46,
"Phil", "Cornell", 8083);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (47,"Allen", "Shacklock", 8083);